# Phase 1: Data Cleaning
In this notebook we load, inspect, and clean the Personal Finance dataset 
in preparation for SQL analysis and visualization.

In [13]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/Personal_Finance_Dataset.csv')
df.head()

,Date,Transaction Description,Category,Amount,Type
0,2020-01-02,Score each.,Food & Drink,1485.69,Expense
1,2020-01-02,Quality throughout.,Utilities,1475.58,Expense
2,2020-01-04,Instead ahead despite measure ago.,Rent,1185.08,Expense
3,2020-01-05,Information last everything thank serve.,Investment,2291.00,Income
4,2020-01-13,Future choice whatever from.,Food & Drink,1126.88,Expense

In [14]:
# Check shape, column names, and data types
print("Shape:", df.shape)
print("\nColumn names:", df.columns.tolist())
print("\nData types:\n", df.dtypes)

Shape: (1500, 5)

Column names: ['Date', 'Transaction Description', 'Category', 'Amount', 'Type']

Data types:
 Date                           str
Transaction Description        str
Category                       str
Amount                     float64
Type                           str
dtype: object

In [15]:
# Identify any missing data
print("Missing values per column:")
print(df.isnull().sum())

Missing values per column:
Date                       0
Transaction Description    0
Category                   0
Amount                     0
Type                       0
dtype: int64

In [16]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [17]:
print("Unique categories:\n", df['Category'].unique())
print("\nTransaction types:\n", df['Type'].unique())

Unique categories:
 <StringArray>
[    'Food & Drink',        'Utilities',             'Rent',
       'Investment',         'Shopping',            'Other',
    'Entertainment', 'Health & Fitness',           'Salary',
           'Travel']
Length: 10, dtype: str

Transaction types:
 <StringArray>
['Expense', 'Income']
Length: 2, dtype: str

## Observations
- No missing values or duplicate rows found
- Date column is stored as string type — needs converting to datetime
- Categories and Type values are clean and consistent
- Amount is float64 which is correct for currency values

In [18]:
# Convert date from string to datetime 
df['Date'] = pd.to_datetime(df['Date'])

print("Date column type after conversion:", df['Date'].dtype)
print("Date range:", df['Date'].min(), "to", df['Date'].max())

Date column type after conversion: datetime64[us]
Date range: 2020-01-02 00:00:00 to 2024-12-29 00:00:00

In [19]:
# Extract month, year and day of week for analysis later
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Month_Name'] = df['Date'].dt.strftime('%B')
df['Day_of_Week'] = df['Date'].dt.strftime('%A')

df.head()

,Date,Transaction Description,Category,Amount,Type,Year,Month,Month_Name,Day_of_Week
0,2020-01-02,Score each.,Food & Drink,1485.69,Expense,2020,1,January,Thursday
1,2020-01-02,Quality throughout.,Utilities,1475.58,Expense,2020,1,January,Thursday
2,2020-01-04,Instead ahead despite measure ago.,Rent,1185.08,Expense,2020,1,January,Saturday
3,2020-01-05,Information last everything thank serve.,Investment,2291.00,Income,2020,1,January,Sunday
4,2020-01-13,Future choice whatever from.,Food & Drink,1126.88,Expense,2020,1,January,Monday

In [20]:
# Remove spaces from column names — makes SQL and pandas easier to work with
df.columns = df.columns.str.replace(' ', '_')

print("Updated column names:", df.columns.tolist())

Updated column names: ['Date', 'Transaction_Description', 'Category', 'Amount', 'Type', 'Year', 'Month', 'Month_Name', 'Day_of_Week']

In [21]:
print("Final shape:", df.shape)
print("\nFinal dtypes:\n", df.dtypes)
df.head()

Final shape: (1500, 9)

Final dtypes:
 Date                       datetime64[us]
Transaction_Description               str
Category                              str
Amount                            float64
Type                                  str
Year                                int32
Month                               int32
Month_Name                            str
Day_of_Week                           str
dtype: object

,Date,Transaction_Description,Category,Amount,Type,Year,Month,Month_Name,Day_of_Week
0,2020-01-02,Score each.,Food & Drink,1485.69,Expense,2020,1,January,Thursday
1,2020-01-02,Quality throughout.,Utilities,1475.58,Expense,2020,1,January,Thursday
2,2020-01-04,Instead ahead despite measure ago.,Rent,1185.08,Expense,2020,1,January,Saturday
3,2020-01-05,Information last everything thank serve.,Investment,2291.00,Income,2020,1,January,Sunday
4,2020-01-13,Future choice whatever from.,Food & Drink,1126.88,Expense,2020,1,January,Monday

In [22]:
# Save cleaned dataset for use in next phases
df.to_csv('../data/cleaned_finance_data.csv', index=False)
print("Cleaned data saved successfully!")

Cleaned data saved successfully!

## Summary
- Converted Date column from string to datetime
- Extracted Year, Month, Month_Name and Day_of_Week columns for time-based analysis
- Renamed columns to remove spaces for easier querying
- Saved cleaned dataset to `data/cleaned_finance_data.csv`

**No major data quality issues found. Dataset is ready for analysis.**